name: Lint
on: [push, pull_request]
jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: PHP-CS-Fixer
          uses: docker://oskarstark/php-cs-fixer-ga
          with:
            args: --diff --dry-run

    phpstan:
        name: phpstan
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: phpstan
          uses: docker://aragon999/phpstan-shopware:v6.4.0
          with:
            args: analyze .
